@echo off
echo Setting up Caroliv Admin Panel...

echo Creating .env.local...
echo NEXT_PUBLIC_API_BASE_URL=http://20.197.14.33:3000/api > .env.local

echo Installing dependencies...
call npm install

echo Starting Admin Panel...
npm run dev
